name: move-terraform-aws
on:
    push:
        branches: 
            - main

env:
    AWS_REGION: "us-east-1"

permissions:
    id-token: write
    contents: read

jobs:
    terraform-deploy:
        name: terraform-deploy
        runs-on: amazon-linux

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
                aws-region: ${{ env.AWS_REGION }}
            
            - name: Apply terraform
              run: terraform init && terraform apply --auto-approve